name: Data Pipeline Job Deployment

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      space:
        type: string
        required: true
      job_type:
        type: string
        required: true
    secrets:
      GIT_TOKEN:
        required: true
      DATABRICKS_HOST:
        required: true 
      DATABRICKS_TOKEN:
        required: true
      FINNHUB_TOKEN:
        required: true
      KAFKA_BOOTSTRAP:
        required: true
      KAFKA_USERNAME:
        required: true
      KAFKA_PASSWORD:
        required: true

jobs:
  deploy-and-launch:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}_${{ inputs.space}}
    env:
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      FINNHUB_TOKEN: ${{ secrets.FINNHUB_TOKEN }}
      KAFKA_BOOTSTRAP: ${{ secrets.KAFKA_BOOTSTRAP }}
      KAFKA_USERNAME: ${{ secrets.KAFKA_USERNAME }}
      KAFKA_PASSWORD: ${{ secrets.KAFKA_PASSWORD }}
      KAFKA_TOPIC: ${{ secrets.KAFKA_TOPIC }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -e ".[dev]"

      # Install Databricks CLI (unified CLI for DAB)
      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
          # Prepend the new CLI path to ensure it's used first
          echo "/usr/local/bin" >> $GITHUB_PATH
          echo "$HOME/.databrickscli" >> $GITHUB_PATH

      - name: Configure Databricks CLI
        run: |
          databricks configure --token <<EOF
          ${{ secrets.DATABRICKS_HOST }}
          ${{ secrets.DATABRICKS_TOKEN }}
          EOF

      - name: Build Wheel
        run: python setup.py bdist_wheel

      # Pass secrets as variables during deployment of desired environment and space
      - name: Deploy DAB job
        run: |
          databricks bundle deploy -t ${{ inputs.environment }}_${{ inputs.space }} \
          --var="finnhub_token=${{ secrets.FINNHUB_TOKEN }}" \
          --var="kafka_bootstrap=${{ secrets.KAFKA_BOOTSTRAP }}" \
          --var="kafka_username=${{ secrets.KAFKA_USERNAME }}" \
          --var="kafka_password=${{ secrets.KAFKA_PASSWORD }}" \
          --var="kafka_topic=${{ secrets.KAFKA_TOPIC }}"

      - name: Launch DAB job
        run: |
          databricks bundle run -t ${{ inputs.environment }}_${{ inputs.space }} finnhub-pipeline \
            --python-named-params env=${{ inputs.environment }} \
            --python-named-params space=${{ inputs.space }} \
            --python-named-params job_type=${{ inputs.job_type }}
      
